<?php

namespace ziya\Translate;


use yii\base\Exception;
use yii\validators\Validator;

class TranslatableValidator extends Validator
{

    public $languages = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \yii\base\Model $model
     * @param string $attribute
     * @throws Exception
     */
    public function validateAttribute($model, $attribute)
    {
        $hasError = false;
        if (empty($this->languages)) {
            throw new Exception('Language list cannot be empty');
        }
        $attributeMessage = [];
        foreach ($this->languages as $language) {
            $val = $model->$attribute;
            if (!isset($val[$language]) ||$val[$language] == null) {
                $hasError = true;
                $attributeMessage []= "{$attribute}_{$language}";
            }
        }
        if ($hasError) {
            $this->addError($model,$attribute,"[ ".implode(", ",$attributeMessage)." ] are required");
        }
    }
}